"""The private pool's coverage against its targets: what to write next.

The pool's ``targets.yaml`` says how many tasks each suite should have at each difficulty::

    docs: {medium: 3, hard: 2}
    scratch-def: {easy: 1, medium: 2, hard: 2}

``forcebench private coverage`` counts the pool's tasks against it (examples left out) and writes
the table to the pool's COVERAGE.md. A cell shows ready tasks against the target, and drafts in
progress after a plus sign; a ready task whose check is stale counts as a draft.
"""

from collections import Counter
from typing import get_args

import yaml
from pydantic import RootModel, ValidationError

from forcebench.pool import PrivatePool, PrivatePoolError
from forcebench.tasks import Difficulty, Task


TARGETS_FILE = "targets.yaml"
COVERAGE_FILE = "COVERAGE.md"
LEVELS: tuple[Difficulty, ...] = get_args(Difficulty)


class Targets(RootModel[dict[str, dict[Difficulty, int]]]):
    """``targets.yaml``: suite -> difficulty -> how many tasks."""


def read_targets(pool: PrivatePool, suites: set[str]) -> dict[str, dict[Difficulty, int]]:
    """The pool's targets, or none before it has any. Refused for a suite that is not public."""
    path = pool.root / TARGETS_FILE
    if not path.exists():
        return {}
    try:
        targets = Targets.model_validate(yaml.safe_load(path.read_text()) or {}).root
    except yaml.YAMLError, ValidationError:
        raise PrivatePoolError(
            f"{TARGETS_FILE} must map suites to {{easy|medium|hard: count}}"
        ) from None
    unknown = sorted(set(targets) - suites)
    if unknown:
        raise PrivatePoolError(f"{TARGETS_FILE}: not public suites: {', '.join(unknown)}")
    return targets


def _counts(tasks: list[Task], pool: PrivatePool) -> tuple[Counter, Counter]:
    ready: Counter[tuple[str, str]] = Counter()
    drafts: Counter[tuple[str, str]] = Counter()
    for t in tasks:
        current = t.id in pool.checks and pool.checks[t.id].task_sha == t.content_sha()
        if t.status == "ready" and current:
            ready[t.suite, t.difficulty] += 1
        elif t.status in ("draft", "ready"):
            drafts[t.suite, t.difficulty] += 1
    return ready, drafts


def table(tasks: list[Task], targets: dict[str, dict[Difficulty, int]], pool: PrivatePool) -> str:
    """COVERAGE.md: per suite and difficulty, ready tasks against the target (+ drafts).

    The table is followed by the cells furthest from their targets.
    """
    ready, drafts = _counts(tasks, pool)
    suites = sorted({*targets, *(s for s, _ in ready + drafts)})

    spans: list[tuple[Difficulty, ...]] = [*((lv,) for lv in LEVELS), LEVELS]  # then the total

    def row(name: str, among: list[str]) -> str:
        cells = []
        for levels in spans:
            r = sum(ready[s, lv] for s in among for lv in levels)
            d = sum(drafts[s, lv] for s in among for lv in levels)
            goal = sum(targets.get(s, {}).get(lv, 0) for s in among for lv in levels)
            cells.append(f"{r}/{goal}" + (f" +{d}" if d else ""))
        return f"| {name} | " + " | ".join(cells) + " |"

    rows = [
        "| suite | " + " | ".join(LEVELS) + " | total |",
        "|---" * (len(LEVELS) + 2) + "|",
        *(row(s, [s]) for s in suites),
        row("**all**", suites),
    ]
    gaps = sorted(
        (
            (target - ready[s, lv] - drafts[s, lv], s, lv)
            for s, t in targets.items()
            for lv, target in t.items()
        ),
        key=lambda g: (-g[0], g[1], LEVELS.index(g[2])),
    )
    todo = [f"- {s}, {lv}: {n} more" for n, s, lv in gaps if n > 0]
    return "\n".join([
        "# Coverage",
        "",
        "Generated by `forcebench private coverage` from targets.yaml: do not edit. Each cell is",
        "ready tasks / target, then drafts in progress (+n). A ready task whose check is stale",
        "counts as a draft. Examples are left out.",
        "",
        *rows,
        "",
        "## To write next",
        "",
        *(todo or ["Every target is met or has drafts under way."]),
        "",
    ])  # fmt: skip
